'on':
  github:
    branches:
      only: develop
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  Test:
    resources:
      instance-type: M4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    run: |
      python -m pip install .
    with:
      script: python tests/integration/gpu.py
