# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: namiyousef/action-python-package-build@main

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: "namiyousef/action-kaggle-gpu-test@main"
        with:
          git_access_token: "${{ secrets.GIT_READ_ONLY_ACCESS_TOKEN }}"
          kaggle_api_key: "${{ secrets.KAGGLE_API_KEY }}"
          repository_name: "${{ github.repository }}"
          test_folder: tests/integration
          
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs:
      - build
      - integration
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
